import type { TradeFlow } from "@/trade/trade-records";
import type { NormalizedFieldKey } from "@/quality/field-mapping-normalized";

export type FieldMappingGroup =
  | "commercial_values"
  | "quantity_weight"
  | "geography_logistics"
  | "hs_product"
  | "anonymous_correlative"
  | "provenance";

export type FieldMappingConfidence = "verified" | "inferred" | "needs_review";

export type FieldMappingDefinition = {
  id: string;
  tradeFlow: TradeFlow;
  group: FieldMappingGroup;
  normalizedField: NormalizedFieldKey;
  label: string;
  rawFields: string[];
  confidence: FieldMappingConfidence;
  note: string;
};

export const fieldMappingDefinitions: FieldMappingDefinition[] = [
  {
    id: "import_declaration_id",
    tradeFlow: "import",
    group: "provenance",
    normalizedField: "declarationIdRaw",
    label: "Declaración / identificación DIN",
    rawFields: ["NUMENCRIPTADO"],
    confidence: "verified",
    note: "Identificador fuente de la declaración; se conserva como texto crudo.",
  },
  {
    id: "export_declaration_id",
    tradeFlow: "export",
    group: "provenance",
    normalizedField: "declarationIdRaw",
    label: "Declaración / identificación DUS",
    rawFields: ["NUMEROIDENT"],
    confidence: "verified",
    note: "Identificador fuente de la declaración; se conserva como texto crudo.",
  },
  {
    id: "import_item_number",
    tradeFlow: "import",
    group: "provenance",
    normalizedField: "itemNumber",
    label: "Número de item",
    rawFields: ["NUMITEM"],
    confidence: "verified",
    note: "Número de item dentro de la declaración.",
  },
  {
    id: "export_item_number",
    tradeFlow: "export",
    group: "provenance",
    normalizedField: "itemNumber",
    label: "Número de item",
    rawFields: ["NUMEROITEM"],
    confidence: "verified",
    note: "Número de item dentro de la declaración.",
  },
  {
    id: "import_acceptance_date",
    tradeFlow: "import",
    group: "provenance",
    normalizedField: "acceptanceDate",
    label: "Fecha de aceptación",
    rawFields: ["FECACEP"],
    confidence: "inferred",
    note: "Fecha normalizada desde formato fuente ddmmaaaa; se conserva también el valor crudo.",
  },
  {
    id: "export_acceptance_date",
    tradeFlow: "export",
    group: "provenance",
    normalizedField: "acceptanceDate",
    label: "Fecha de aceptación",
    rawFields: ["FECHAACEPT"],
    confidence: "inferred",
    note: "Fecha normalizada desde formato fuente ddmmaaaa; se conserva también el valor crudo.",
  },
  {
    id: "import_importer_correlative",
    tradeFlow: "import",
    group: "anonymous_correlative",
    normalizedField: "importerCorrelativeId",
    label: "Correlativo anónimo importador",
    rawFields: ["NUM_UNICO_IMPORTADOR"],
    confidence: "verified",
    note: "Identificador anónimo de Aduana. No es RUT, razón social ni identidad legal verificada.",
  },
  {
    id: "export_exporter_primary_correlative",
    tradeFlow: "export",
    group: "anonymous_correlative",
    normalizedField: "exporterPrimaryCorrelativeId",
    label: "Correlativo anónimo exportador principal",
    rawFields: ["NRO_EXPORTADOR"],
    confidence: "verified",
    note: "Identificador anónimo de Aduana. No es RUT, razón social ni identidad legal verificada.",
  },
  {
    id: "export_exporter_secondary_correlative",
    tradeFlow: "export",
    group: "anonymous_correlative",
    normalizedField: "exporterSecondaryCorrelativeId",
    label: "Correlativo anónimo exportador secundario",
    rawFields: ["NRO_EXPORTADOR_SEC"],
    confidence: "verified",
    note: "Identificador anónimo de Aduana. Muchos registros no traen exportador secundario.",
  },
  {
    id: "import_hs_raw",
    tradeFlow: "import",
    group: "hs_product",
    normalizedField: "hsCodeRaw",
    label: "Código arancelario fuente",
    rawFields: ["ARANC-NAC"],
    confidence: "verified",
    note: "Código arancelario fuente antes de normalizar dígitos.",
  },
  {
    id: "export_hs_raw",
    tradeFlow: "export",
    group: "hs_product",
    normalizedField: "hsCodeRaw",
    label: "Código arancelario fuente",
    rawFields: ["CODIGOARANCEL"],
    confidence: "verified",
    note: "Código arancelario fuente antes de normalizar dígitos.",
  },
  {
    id: "import_hs_normalized",
    tradeFlow: "import",
    group: "hs_product",
    normalizedField: "hsCodeNormalized",
    label: "Código HS normalizado",
    rawFields: ["ARANC-NAC"],
    confidence: "inferred",
    note: "Se conservan solo dígitos para filtros por prefijo; validar contra diccionario HS antes de uso oficial.",
  },
  {
    id: "export_hs_normalized",
    tradeFlow: "export",
    group: "hs_product",
    normalizedField: "hsCodeNormalized",
    label: "Código HS normalizado",
    rawFields: ["CODIGOARANCEL"],
    confidence: "inferred",
    note: "Se conservan solo dígitos para filtros por prefijo; validar contra diccionario HS antes de uso oficial.",
  },
  {
    id: "import_product_description",
    tradeFlow: "import",
    group: "hs_product",
    normalizedField: "productDescriptionRaw",
    label: "Descripción producto",
    rawFields: ["DNOMBRE"],
    confidence: "verified",
    note: "Texto fuente principal del producto; puede contener abreviaturas o escritura operativa.",
  },
  {
    id: "export_product_description",
    tradeFlow: "export",
    group: "hs_product",
    normalizedField: "productDescriptionRaw",
    label: "Descripción producto",
    rawFields: ["NOMBRE"],
    confidence: "verified",
    note: "Texto fuente principal del producto; puede contener abreviaturas o escritura operativa.",
  },
  {
    id: "import_product_attributes",
    tradeFlow: "import",
    group: "hs_product",
    normalizedField: "productAttributes",
    label: "Atributos de producto",
    rawFields: ["DMARCA", "DVARIEDAD", "DOTRO1", "DOTRO2", "ATR-5", "ATR-6"],
    confidence: "verified",
    note: "Atributos fuente agrupados en JSON para revisión y búsqueda; no equivalen a identidad de empresa.",
  },
  {
    id: "export_product_attributes",
    tradeFlow: "export",
    group: "hs_product",
    normalizedField: "productAttributes",
    label: "Atributos de producto",
    rawFields: ["ATRIBUTO1", "ATRIBUTO2", "ATRIBUTO3", "ATRIBUTO4", "ATRIBUTO5", "ATRIBUTO6"],
    confidence: "verified",
    note: "Atributos fuente agrupados en JSON para revisión y búsqueda; no equivalen a identidad de empresa.",
  },
  {
    id: "import_product_search",
    tradeFlow: "import",
    group: "hs_product",
    normalizedField: "productSearchText",
    label: "Texto de búsqueda producto",
    rawFields: ["DNOMBRE", "DMARCA", "DVARIEDAD", "DOTRO1", "DOTRO2", "ATR-5", "ATR-6"],
    confidence: "inferred",
    note: "Campo derivado para búsqueda; combina descripción y atributos sin cambiar el texto fuente.",
  },
  {
    id: "export_product_search",
    tradeFlow: "export",
    group: "hs_product",
    normalizedField: "productSearchText",
    label: "Texto de búsqueda producto",
    rawFields: ["NOMBRE", "ATRIBUTO1", "ATRIBUTO2", "ATRIBUTO3", "ATRIBUTO4", "ATRIBUTO5", "ATRIBUTO6"],
    confidence: "inferred",
    note: "Campo derivado para búsqueda; combina descripción y atributos sin cambiar el texto fuente.",
  },
  {
    id: "import_quantity",
    tradeFlow: "import",
    group: "quantity_weight",
    normalizedField: "quantity",
    label: "Cantidad mercancía",
    rawFields: ["CANT-MERC"],
    confidence: "inferred",
    note: "Número parseado desde coma decimal; comparar solo junto con unidad.",
  },
  {
    id: "export_quantity",
    tradeFlow: "export",
    group: "quantity_weight",
    normalizedField: "quantity",
    label: "Cantidad mercancía",
    rawFields: ["CANTIDADMERCANCIA"],
    confidence: "inferred",
    note: "Número parseado desde coma decimal; comparar solo junto con unidad.",
  },
  {
    id: "import_quantity_unit",
    tradeFlow: "import",
    group: "quantity_weight",
    normalizedField: "quantityUnitCode",
    label: "Unidad de medida",
    rawFields: ["MEDIDA"],
    confidence: "verified",
    note: "Código fuente de unidad; requiere tabla de códigos para etiqueta comercial.",
  },
  {
    id: "export_quantity_unit",
    tradeFlow: "export",
    group: "quantity_weight",
    normalizedField: "quantityUnitCode",
    label: "Unidad de medida",
    rawFields: ["UNIDADMEDIDA"],
    confidence: "verified",
    note: "Código fuente de unidad; requiere tabla de códigos para etiqueta comercial.",
  },
  {
    id: "import_gross_weight_total",
    tradeFlow: "import",
    group: "quantity_weight",
    normalizedField: "grossWeightTotal",
    label: "Peso bruto total",
    rawFields: ["TOT_PESO"],
    confidence: "inferred",
    note: "Peso total de la declaración/registro fuente; no debe confundirse con peso item.",
  },
  {
    id: "export_gross_weight_total",
    tradeFlow: "export",
    group: "quantity_weight",
    normalizedField: "grossWeightTotal",
    label: "Peso bruto total",
    rawFields: ["PESOBRUTOTOTAL"],
    confidence: "inferred",
    note: "Peso total de la declaración/registro fuente; no debe confundirse con peso item.",
  },
  {
    id: "import_gross_weight_item",
    tradeFlow: "import",
    group: "quantity_weight",
    normalizedField: "grossWeightItem",
    label: "Peso bruto item",
    rawFields: [],
    confidence: "needs_review",
    note: "El layout DIN March 2026 no contiene un campo de peso bruto por item; TOT_PESO es peso total y no debe usarse como aproximación automática.",
  },
  {
    id: "export_gross_weight_item",
    tradeFlow: "export",
    group: "quantity_weight",
    normalizedField: "grossWeightItem",
    label: "Peso bruto item",
    rawFields: ["PESOBRUTOITEM"],
    confidence: "inferred",
    note: "Peso item disponible en DUS; comparar contra peso total en revisiones agregadas.",
  },
  {
    id: "import_item_cif_value",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "itemCifValue",
    label: "Valor CIF item",
    rawFields: ["CIF-ITEM"],
    confidence: "inferred",
    note: "Métrica comercial principal para importaciones; parseada desde coma decimal.",
  },
  {
    id: "export_item_fob_value",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "itemFobValue",
    label: "Valor FOB item",
    rawFields: ["FOBUS"],
    confidence: "inferred",
    note: "Métrica comercial principal para exportaciones; parseada desde coma decimal.",
  },
  {
    id: "import_declaration_fob",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "declarationFobValue",
    label: "FOB declaración",
    rawFields: ["FOB"],
    confidence: "inferred",
    note: "Valor FOB de declaración; no reemplaza CIF item para ranking de importación.",
  },
  {
    id: "export_declaration_fob",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "declarationFobValue",
    label: "FOB declaración",
    rawFields: ["TOTALVALORFOB"],
    confidence: "inferred",
    note: "Valor FOB total de declaración; útil para contexto agregado de exportación.",
  },
  {
    id: "import_freight",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "freightValue",
    label: "Flete",
    rawFields: ["FLETE"],
    confidence: "inferred",
    note: "Componente de costo importación; revisar moneda/alcance antes de comparar entre fuentes.",
  },
  {
    id: "export_freight",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "freightValue",
    label: "Flete",
    rawFields: ["VALORFLETE"],
    confidence: "inferred",
    note: "Componente logístico exportación; puede no ser la métrica principal de valor comercial.",
  },
  {
    id: "import_insurance",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "insuranceValue",
    label: "Seguro",
    rawFields: ["SEGURO"],
    confidence: "inferred",
    note: "Componente de costo importación; revisar con CIF y flete.",
  },
  {
    id: "export_insurance",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "insuranceValue",
    label: "Seguro",
    rawFields: ["VALORSEGURO"],
    confidence: "inferred",
    note: "Componente logístico exportación; puede venir en cero sin invalidar FOB.",
  },
  {
    id: "import_cif_declaration",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "cifValue",
    label: "CIF declaración",
    rawFields: ["CIF"],
    confidence: "inferred",
    note: "Valor CIF de declaración; usar junto a CIF item y componentes de costo.",
  },
  {
    id: "export_cif_declaration",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "cifValue",
    label: "CIF exportación",
    rawFields: ["VALORCIF"],
    confidence: "inferred",
    note: "Campo fuente normalizado como contexto secundario; FOB sigue siendo la lectura principal de exportación y los ceros no son defecto automático.",
  },
  {
    id: "import_unit_price",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "unitPriceValue",
    label: "Precio unitario",
    rawFields: ["PRE-UNIT"],
    confidence: "inferred",
    note: "Precio unitario fuente; solo comparable cuando unidad y moneda son consistentes.",
  },
  {
    id: "export_unit_price",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "unitPriceValue",
    label: "Precio unitario FOB",
    rawFields: ["FOBUNITARIO"],
    confidence: "inferred",
    note: "Precio unitario fuente; solo comparable cuando unidad y moneda son consistentes.",
  },
  {
    id: "import_currency",
    tradeFlow: "import",
    group: "commercial_values",
    normalizedField: "currencyCodeRaw",
    label: "Moneda",
    rawFields: ["MONEDA"],
    confidence: "verified",
    note: "Código fuente de moneda; requiere tabla de códigos para etiqueta.",
  },
  {
    id: "export_currency",
    tradeFlow: "export",
    group: "commercial_values",
    normalizedField: "currencyCodeRaw",
    label: "Moneda",
    rawFields: ["MONEDA"],
    confidence: "verified",
    note: "Código fuente de moneda; requiere tabla de códigos para etiqueta.",
  },
  {
    id: "import_origin_country",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "originCountryCode",
    label: "País de origen",
    rawFields: ["PA_ORIG"],
    confidence: "verified",
    note: "Código fuente; la etiqueta depende de tablas Aduana cargadas.",
  },
  {
    id: "import_acquisition_country",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "acquisitionCountryCode",
    label: "País de adquisición",
    rawFields: ["PA_ADQ"],
    confidence: "verified",
    note: "Código fuente; no siempre equivale al país de origen.",
  },
  {
    id: "import_consignment_country",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "consignmentCountryCode",
    label: "País de consignación",
    rawFields: ["CODPAISCON"],
    confidence: "verified",
    note: "Código fuente; útil para logística, no para origen si difiere de PA_ORIG.",
  },
  {
    id: "export_destination_country",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "destinationCountryCode",
    label: "País de destino",
    rawFields: ["PAISDESTINO"],
    confidence: "verified",
    note: "Código fuente; dimensión comercial principal de destino exportador.",
  },
  {
    id: "export_destination_country_label",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "destinationCountryLabelRaw",
    label: "Glosa país destino",
    rawFields: ["GLOSAPAISDESTINO"],
    confidence: "verified",
    note: "Glosa fuente; convive con la etiqueta decodificada desde tabla de códigos.",
  },
  {
    id: "import_customs_office",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "customsOfficeCode",
    label: "Aduana",
    rawFields: ["ADU"],
    confidence: "verified",
    note: "Código fuente de aduana; revisar faltantes de decodificación en QA.",
  },
  {
    id: "export_customs_office",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "customsOfficeCode",
    label: "Aduana",
    rawFields: ["ADUANA"],
    confidence: "verified",
    note: "Código fuente de aduana; revisar faltantes de decodificación en QA.",
  },
  {
    id: "import_embark_port",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "embarkPortCode",
    label: "Puerto de embarque",
    rawFields: ["PTO_EMB"],
    confidence: "verified",
    note: "Código fuente de puerto de embarque; para importación el puerto relevante de llegada suele ser desembarque.",
  },
  {
    id: "export_embark_port",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "embarkPortCode",
    label: "Puerto de embarque",
    rawFields: ["PUERTOEMB"],
    confidence: "verified",
    note: "Código fuente de puerto de embarque; dimensión logística relevante en exportación.",
  },
  {
    id: "export_embark_port_label",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "embarkPortLabelRaw",
    label: "Glosa puerto embarque",
    rawFields: ["GLOSAPUERTOEMB"],
    confidence: "verified",
    note: "Glosa fuente; convive con la etiqueta decodificada desde tabla de códigos.",
  },
  {
    id: "import_disembark_port",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "disembarkPortCode",
    label: "Puerto de desembarque",
    rawFields: ["PTO_DESEM"],
    confidence: "verified",
    note: "Código fuente de puerto de desembarque; dimensión logística relevante en importación.",
  },
  {
    id: "export_disembark_port",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "disembarkPortCode",
    label: "Puerto de desembarque",
    rawFields: ["PUERTODESEMB"],
    confidence: "verified",
    note: "Código fuente de puerto de desembarque; en exportación suele ser contexto de destino/logística.",
  },
  {
    id: "export_disembark_port_label",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "disembarkPortLabelRaw",
    label: "Glosa puerto desembarque",
    rawFields: ["GLOSAPUERTODESEMB"],
    confidence: "verified",
    note: "Glosa fuente; convive con la etiqueta decodificada desde tabla de códigos.",
  },
  {
    id: "import_transport_mode",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "transportModeCode",
    label: "Vía de transporte",
    rawFields: ["VIA_TRAN"],
    confidence: "verified",
    note: "Código fuente de vía; revisar faltantes de decodificación en QA.",
  },
  {
    id: "export_transport_mode",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "transportModeCode",
    label: "Vía de transporte",
    rawFields: ["VIATRANSPORTE"],
    confidence: "verified",
    note: "Código fuente de vía; revisar faltantes de decodificación en QA.",
  },
  {
    id: "import_cargo_type",
    tradeFlow: "import",
    group: "geography_logistics",
    normalizedField: "cargoTypeCode",
    label: "Tipo de carga",
    rawFields: ["TPO_CARGA"],
    confidence: "verified",
    note: "Código fuente de tipo de carga; etiqueta completa depende de tabla oficial.",
  },
  {
    id: "export_cargo_type",
    tradeFlow: "export",
    group: "geography_logistics",
    normalizedField: "cargoTypeCode",
    label: "Tipo de carga",
    rawFields: ["TIPOCARGA"],
    confidence: "verified",
    note: "Código fuente de tipo de carga; etiqueta completa depende de tabla oficial.",
  },
];

export function fieldMappingGroupLabel(group: FieldMappingGroup) {
  const labels: Record<FieldMappingGroup, string> = {
    commercial_values: "Valores comerciales",
    quantity_weight: "Cantidad y peso",
    geography_logistics: "Geografía y logística",
    hs_product: "HS y producto",
    anonymous_correlative: "Correlativos anónimos",
    provenance: "Proveniencia",
  };

  return labels[group];
}

export function fieldMappingConfidenceLabel(confidence: FieldMappingConfidence) {
  const labels: Record<FieldMappingConfidence, string> = {
    verified: "Mapeo directo",
    inferred: "Normalizado",
    needs_review: "Requiere revisión",
  };

  return labels[confidence];
}
