import { createHash } from "node:crypto";
import { createReadStream, existsSync, statSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { config } from "dotenv";
import {
  HeadObjectCommand,
  ListObjectsV2Command,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";

type PlanObject = {
  localPath: string;
  r2Bucket: string;
  r2Key: string | null;
  classification: string;
  sizeBytes: number;
  sha256: string;
  includeInUpload: boolean;
  metadata: Record<string, string>;
};

type ArchivePlan = {
  mode: string;
  uploadAttempted: boolean;
  bucket: string;
  errors: string[];
  warnings: string[];
  objects: PlanObject[];
};

type Env = {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
  endpoint: string;
};

type Args = {
  confirmUpload: boolean;
  includeClassifications: Set<string>;
  limit: number | null;
  planFile: string;
  verifyOnly: boolean;
};

const repoRoot = process.cwd();
const defaultPlanFile = "/tmp/duanera-r2-upload-plan.json";
const defaultClassifications = new Set(["official_source_raw"]);
const maxSinglePutObjectBytes = 5 * 1024 * 1024 * 1024;

config({ path: ".env.local", quiet: true });

function parseArgs(argv: string[]): Args {
  const args: Args = {
    confirmUpload: false,
    includeClassifications: new Set(defaultClassifications),
    limit: null,
    planFile: defaultPlanFile,
    verifyOnly: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--confirm-upload") {
      args.confirmUpload = true;
      continue;
    }

    if (arg === "--verify-only") {
      args.verifyOnly = true;
      continue;
    }

    if (arg === "--plan-file") {
      args.planFile = requiredValue(argv, index, arg);
      index += 1;
      continue;
    }

    if (arg === "--include-classification") {
      const value = requiredValue(argv, index, arg);
      args.includeClassifications.add(value);
      index += 1;
      continue;
    }

    if (arg === "--only-classification") {
      const value = requiredValue(argv, index, arg);
      args.includeClassifications = new Set([value]);
      index += 1;
      continue;
    }

    if (arg === "--limit") {
      const value = Number(requiredValue(argv, index, arg));
      if (!Number.isInteger(value) || value < 1) {
        throw new Error("--limit must be a positive integer.");
      }
      args.limit = value;
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return args;
}

function requiredValue(argv: string[], index: number, flag: string) {
  const value = argv[index + 1];
  if (!value || value.startsWith("--")) {
    throw new Error(`${flag} requires a value.`);
  }
  return value;
}

function requireEnv(name: string) {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} is missing from .env.local.`);
  }
  return value;
}

function readEnv(): Env {
  const accountId = requireEnv("CLOUDFLARE_ACCOUNT_ID");
  const endpoint = requireEnv("R2_ENDPOINT");

  return {
    accountId,
    accessKeyId: requireEnv("R2_ACCESS_KEY_ID"),
    secretAccessKey: requireEnv("R2_SECRET_ACCESS_KEY"),
    bucket: requireEnv("R2_BUCKET"),
    endpoint,
  };
}

function assertEndpointMatchesAccount(env: Env) {
  const expectedHost = `${env.accountId}.r2.cloudflarestorage.com`;
  const endpoint = new URL(env.endpoint);
  if (endpoint.hostname !== expectedHost) {
    throw new Error(`R2_ENDPOINT host does not match CLOUDFLARE_ACCOUNT_ID. Expected ${expectedHost}.`);
  }
}

function createClient(env: Env) {
  return new S3Client({
    region: "auto",
    endpoint: env.endpoint,
    credentials: {
      accessKeyId: env.accessKeyId,
      secretAccessKey: env.secretAccessKey,
    },
  });
}

async function verifyBucketAccess(client: S3Client, bucket: string) {
  const response = await client.send(
    new ListObjectsV2Command({
      Bucket: bucket,
      MaxKeys: 1,
    }),
  );

  return {
    bucket,
    objectSampleCount: response.Contents?.length ?? 0,
    keyCountKnown: response.KeyCount ?? null,
    isTruncated: response.IsTruncated ?? false,
  };
}

async function readPlan(planFile: string): Promise<ArchivePlan> {
  const content = await readFile(planFile, "utf8");
  const plan = JSON.parse(content) as ArchivePlan;

  if (plan.mode !== "dry-run" || plan.uploadAttempted !== false) {
    throw new Error("Plan file must be generated by the dry-run archive planner.");
  }

  if (plan.errors.length > 0) {
    throw new Error(`Plan file has ${plan.errors.length} validation error(s). Regenerate and fix it first.`);
  }

  if (plan.warnings.length > 0) {
    throw new Error(`Plan file has ${plan.warnings.length} warning(s). Review and fix them before uploading.`);
  }

  return plan;
}

function selectObjects(plan: ArchivePlan, args: Args, env: Env) {
  if (plan.bucket !== env.bucket) {
    throw new Error(`Plan bucket ${plan.bucket} does not match R2_BUCKET ${env.bucket}.`);
  }

  const selected = plan.objects.filter((object) => {
    return (
      object.includeInUpload &&
      object.r2Key &&
      args.includeClassifications.has(object.classification)
    );
  });

  return args.limit ? selected.slice(0, args.limit) : selected;
}

function verifyLocalFile(object: PlanObject) {
  const absolutePath = path.resolve(repoRoot, object.localPath);
  if (!existsSync(absolutePath)) {
    throw new Error(`${object.localPath}: local file is missing.`);
  }

  const sizeBytes = statSync(absolutePath).size;
  if (sizeBytes !== object.sizeBytes) {
    throw new Error(`${object.localPath}: local size ${sizeBytes} does not match plan size ${object.sizeBytes}.`);
  }

  if (sizeBytes >= maxSinglePutObjectBytes) {
    throw new Error(`${object.localPath}: file is too large for this single-object upload script.`);
  }

  return absolutePath;
}

function sha256File(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = createHash("sha256");
    const stream = createReadStream(filePath);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("error", reject);
    stream.on("end", () => resolve(hash.digest("hex")));
  });
}

function isMissingObjectError(error: unknown) {
  if (!error || typeof error !== "object") {
    return false;
  }

  const candidate = error as { name?: string; $metadata?: { httpStatusCode?: number } };
  return candidate.name === "NotFound" || candidate.name === "NoSuchKey" || candidate.$metadata?.httpStatusCode === 404;
}

async function headObjectMetadata(client: S3Client, bucket: string, key: string) {
  try {
    const head = await client.send(
      new HeadObjectCommand({
        Bucket: bucket,
        Key: key,
      }),
    );

    return {
      sizeBytes: head.ContentLength ?? null,
      sha256: head.Metadata?.sha256 ?? null,
    };
  } catch (error) {
    if (isMissingObjectError(error)) {
      return null;
    }
    throw error;
  }
}

async function uploadObject(client: S3Client, bucket: string, object: PlanObject) {
  if (!object.r2Key) {
    throw new Error(`${object.localPath}: missing R2 key.`);
  }

  const absolutePath = verifyLocalFile(object);
  const sha256 = await sha256File(absolutePath);
  if (sha256 !== object.sha256) {
    throw new Error(`${object.localPath}: local SHA-256 no longer matches the plan.`);
  }

  const existingObject = await headObjectMetadata(client, bucket, object.r2Key);
  if (existingObject) {
    if (existingObject.sizeBytes === object.sizeBytes && existingObject.sha256 === object.sha256) {
      return "verified-existing";
    }

    throw new Error(`${object.r2Key}: remote object already exists with different size or SHA-256 metadata.`);
  }

  await client.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: object.r2Key,
      Body: createReadStream(absolutePath),
      ContentLength: object.sizeBytes,
      Metadata: object.metadata,
    }),
  );

  const head = await headObjectMetadata(client, bucket, object.r2Key);

  if (!head) {
    throw new Error(`${object.r2Key}: remote object was not found after upload.`);
  }

  if (head.sizeBytes !== object.sizeBytes) {
    throw new Error(`${object.r2Key}: remote size ${head.sizeBytes} does not match local size ${object.sizeBytes}.`);
  }

  if (head.sha256 !== object.sha256) {
    throw new Error(`${object.r2Key}: remote SHA-256 metadata does not match local checksum.`);
  }

  return "uploaded";
}

function summarizeSelection(objects: PlanObject[]) {
  const summary: Record<string, { files: number; bytes: number }> = {};
  for (const object of objects) {
    summary[object.classification] ??= { files: 0, bytes: 0 };
    summary[object.classification].files += 1;
    summary[object.classification].bytes += object.sizeBytes;
  }
  return summary;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const env = readEnv();
  assertEndpointMatchesAccount(env);
  const client = createClient(env);

  const access = await verifyBucketAccess(client, env.bucket);
  process.stdout.write(
    JSON.stringify(
      {
        env: {
          CLOUDFLARE_ACCOUNT_ID: "set",
          R2_ACCESS_KEY_ID: "set",
          R2_SECRET_ACCESS_KEY: "set",
          R2_BUCKET: "set",
          R2_ENDPOINT: "set",
        },
        access,
      },
      null,
      2,
    ),
  );
  process.stdout.write("\n");

  if (args.verifyOnly) {
    return;
  }

  const plan = await readPlan(args.planFile);
  const selected = selectObjects(plan, args, env);
  const uploadConfirmed = args.confirmUpload && process.env.R2_UPLOAD_CONFIRM === "upload";

  if (args.confirmUpload && process.env.R2_UPLOAD_CONFIRM !== "upload") {
    throw new Error("Set R2_UPLOAD_CONFIRM=upload as a second confirmation before uploading.");
  }

  process.stdout.write(
    JSON.stringify(
      {
        mode: uploadConfirmed ? "upload" : "dry-run",
        uploadAttempted: uploadConfirmed,
        planFile: args.planFile,
        includedClassifications: [...args.includeClassifications].sort(),
        selectedObjects: selected.length,
        selectedSummary: summarizeSelection(selected),
      },
      null,
      2,
    ),
  );
  process.stdout.write("\n");

  if (!uploadConfirmed) {
    return;
  }

  for (const object of selected) {
    const result = await uploadObject(client, env.bucket, object);
    process.stdout.write(`${result} ${object.r2Key}\n`);
  }
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`R2 archive upload workflow failed: ${message}\n`);
  process.exitCode = 1;
});
