import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { config } from "dotenv";
import { S3Client } from "@aws-sdk/client-s3";
import path from "node:path";

import {
  parsePositiveSafeIntegerCliValue,
  requiredCliValue,
} from "../../src/lib/cli-args";
import {
  uploadObject,
  verifyBucketAccess,
} from "./r2-upload-objects";
import {
  parseArchivePlan,
  type ArchivePlan,
  type PlanObject,
} from "./r2-upload-plan-parser";
export {
  parseArchivePlan,
  type ArchivePlan,
  type PlanObject,
} from "./r2-upload-plan-parser";
export {
  resolvePlanLocalPath,
  verifyLocalFile,
} from "./r2-upload-objects";

type Env = {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
  endpoint: string;
};

type Args = {
  confirmUpload: boolean;
  includeClassifications: Set<string>;
  limit: number | null;
  planFile: string;
  verifyOnly: boolean;
};

const repoRoot = process.cwd();
const defaultPlanFile = "/tmp/duanera-r2-upload-plan.json";
const defaultClassifications = new Set(["official_source_raw"]);

export function parseArchiveUploadArgs(argv: string[]): Args {
  const args: Args = {
    confirmUpload: false,
    includeClassifications: new Set(defaultClassifications),
    limit: null,
    planFile: defaultPlanFile,
    verifyOnly: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--confirm-upload") {
      args.confirmUpload = true;
      continue;
    }

    if (arg === "--verify-only") {
      args.verifyOnly = true;
      continue;
    }

    if (arg === "--plan-file") {
      args.planFile = requiredCliValue(argv, index, arg);
      index += 1;
      continue;
    }

    if (arg === "--include-classification") {
      const value = requiredCliValue(argv, index, arg);
      args.includeClassifications.add(value);
      index += 1;
      continue;
    }

    if (arg === "--only-classification") {
      const value = requiredCliValue(argv, index, arg);
      args.includeClassifications = new Set([value]);
      index += 1;
      continue;
    }

    if (arg === "--limit") {
      args.limit = parsePositiveSafeIntegerCliValue(
        requiredCliValue(argv, index, arg),
        arg,
      );
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return args;
}

function requireEnv(name: string) {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} is missing from .env.local.`);
  }
  return value;
}

function readEnv(): Env {
  const accountId = requireEnv("CLOUDFLARE_ACCOUNT_ID");
  const endpoint = requireEnv("R2_ENDPOINT");

  return {
    accountId,
    accessKeyId: requireEnv("R2_ACCESS_KEY_ID"),
    secretAccessKey: requireEnv("R2_SECRET_ACCESS_KEY"),
    bucket: requireEnv("R2_BUCKET"),
    endpoint,
  };
}

function assertEndpointMatchesAccount(env: Env) {
  const expectedHost = `${env.accountId}.r2.cloudflarestorage.com`;
  const endpoint = new URL(env.endpoint);
  if (endpoint.hostname !== expectedHost) {
    throw new Error(`R2_ENDPOINT host does not match CLOUDFLARE_ACCOUNT_ID. Expected ${expectedHost}.`);
  }
}

function createClient(env: Env) {
  return new S3Client({
    region: "auto",
    endpoint: env.endpoint,
    credentials: {
      accessKeyId: env.accessKeyId,
      secretAccessKey: env.secretAccessKey,
    },
  });
}

async function readPlan(planFile: string): Promise<ArchivePlan> {
  const content = await readFile(planFile, "utf8");
  const plan = parseArchivePlan(content);

  if (plan.mode !== "dry-run" || plan.uploadAttempted !== false) {
    throw new Error("Plan file must be generated by the dry-run archive planner.");
  }

  if (plan.errors.length > 0) {
    throw new Error(`Plan file has ${plan.errors.length} validation error(s). Regenerate and fix it first.`);
  }

  if (plan.warnings.length > 0) {
    throw new Error(`Plan file has ${plan.warnings.length} warning(s). Review and fix them before uploading.`);
  }

  return plan;
}

function selectObjects(plan: ArchivePlan, args: Args, env: Env) {
  if (plan.bucket !== env.bucket) {
    throw new Error(`Plan bucket ${plan.bucket} does not match R2_BUCKET ${env.bucket}.`);
  }

  const selected = plan.objects.filter((object) => {
    return (
      object.includeInUpload &&
      object.r2Key &&
      args.includeClassifications.has(object.classification)
    );
  });

  return args.limit ? selected.slice(0, args.limit) : selected;
}


function summarizeSelection(objects: PlanObject[]) {
  const summary: Record<string, { files: number; bytes: number }> = {};
  for (const object of objects) {
    summary[object.classification] ??= { files: 0, bytes: 0 };
    summary[object.classification].files += 1;
    summary[object.classification].bytes += object.sizeBytes;
  }
  return summary;
}

async function main() {
  config({ path: ".env.local", quiet: true });

  const args = parseArchiveUploadArgs(process.argv.slice(2));
  const env = readEnv();
  assertEndpointMatchesAccount(env);
  const client = createClient(env);

  const access = await verifyBucketAccess(client, env.bucket);
  process.stdout.write(
    JSON.stringify(
      {
        env: {
          CLOUDFLARE_ACCOUNT_ID: "set",
          R2_ACCESS_KEY_ID: "set",
          R2_SECRET_ACCESS_KEY: "set",
          R2_BUCKET: "set",
          R2_ENDPOINT: "set",
        },
        access,
      },
      null,
      2,
    ),
  );
  process.stdout.write("\n");

  if (args.verifyOnly) {
    return;
  }

  const plan = await readPlan(args.planFile);
  const selected = selectObjects(plan, args, env);
  const uploadConfirmed = args.confirmUpload && process.env.R2_UPLOAD_CONFIRM === "upload";

  if (args.confirmUpload && process.env.R2_UPLOAD_CONFIRM !== "upload") {
    throw new Error("Set R2_UPLOAD_CONFIRM=upload as a second confirmation before uploading.");
  }

  process.stdout.write(
    JSON.stringify(
      {
        mode: uploadConfirmed ? "upload" : "dry-run",
        uploadAttempted: uploadConfirmed,
        planFile: args.planFile,
        includedClassifications: [...args.includeClassifications].sort(),
        selectedObjects: selected.length,
        selectedSummary: summarizeSelection(selected),
      },
      null,
      2,
    ),
  );
  process.stdout.write("\n");

  if (!uploadConfirmed) {
    return;
  }

  for (const object of selected) {
    const result = await uploadObject(client, env.bucket, object);
    process.stdout.write(`${result} ${object.r2Key}\n`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`R2 archive upload workflow failed: ${message}\n`);
    process.exitCode = 1;
  });
}
