export const importFieldNames = [
  "NUMENCRIPTADO",
  "TIPO_DOCTO",
  "ADU",
  "FORM",
  "FECVENCI",
  "CODCOMUN",
  "NUM_UNICO_IMPORTADOR",
  "CODPAISCON",
  "DESDIRALM",
  "CODCOMRS",
  "ADUCTROL",
  "NUMPLAZO",
  "INDPARCIAL",
  "NUMHOJINS",
  "TOTINSUM",
  "CODALMA",
  "NUM_RS",
  "FEC_RS",
  "ADUA_RS",
  "NUMHOJANE",
  "NUM_SEC",
  "PA_ORIG",
  "PA_ADQ",
  "VIA_TRAN",
  "TRANSB",
  "PTO_EMB",
  "PTO_DESEM",
  "TPO_CARGA",
  "ALMACEN",
  "FEC_ALMAC",
  "FECRETIRO",
  "NU_REGR",
  "ANO_REG",
  "CODVISBUEN",
  "NUMREGLA",
  "NUMANORES",
  "CODULTVB",
  "PAGO_GRAV",
  "FECTRA",
  "FECACEP",
  "GNOM_CIA_T",
  "CODPAISCIA",
  "NUMRUTCIA",
  "DIGVERCIA",
  "NUM_MANIF",
  "NUM_MANIF1",
  "NUM_MANIF2",
  "FEC_MANIF",
  "NUM_CONOC",
  "FEC_CONOC",
  "NOMEMISOR",
  "NUMRUTEMI",
  "DIGVEREMI",
  "GREG_IMP",
  "REG_IMP",
  "BCO_COM",
  "CODORDIV",
  "FORM_PAGO",
  "NUMDIAS",
  "VALEXFAB",
  "MONEDA",
  "MONGASFOB",
  "CL_COMPRA",
  "TOT_ITEMS",
  "FOB",
  "TOT_HOJAS",
  "COD_FLE",
  "FLETE",
  "TOT_BULTOS",
  "COD_SEG",
  "SEGURO",
  "TOT_PESO",
  "CIF",
  "NUM_AUT",
  "FEC_AUT",
  "GBCOCEN",
  "ID_BULTOS",
  "TPO_BUL1",
  "CANT_BUL1",
  "TPO_BUL2",
  "CANT_BUL2",
  "TPO_BUL3",
  "CANT_BUL3",
  "TPO_BUL4",
  "CANT_BUL4",
  "TPO_BUL5",
  "CANT_BUL5",
  "TPO_BUL6",
  "CANT_BUL6",
  "TPO_BUL7",
  "CANT_BUL7",
  "TPO_BUL8",
  "CANT_BUL8",
  "CTA_OTRO",
  "MON_OTRO",
  "CTA_OTR1",
  "MON_OTR1",
  "CTA_OTR2",
  "MON_OTR2",
  "CTA_OTR3",
  "MON_OTR3",
  "CTA_OTR4",
  "MON_OTR4",
  "CTA_OTR5",
  "MON_OTR5",
  "CTA_OTR6",
  "MON_OTR6",
  "CTA_OTR7",
  "MON_OTR7",
  "MON_178",
  "MON_191",
  "FEC_501",
  "VAL_601",
  "FEC_502",
  "VAL_602",
  "FEC_503",
  "VAL_603",
  "FEC_504",
  "VAL_604",
  "FEC_505",
  "VAL_605",
  "FEC_506",
  "VAL_606",
  "FEC_507",
  "VAL_607",
  "TASA",
  "NCUOTAS",
  "ADU_DI",
  "NUM_DI",
  "FEC_DI",
  "MON_699",
  "MON_199",
  "NUMITEM",
  "DNOMBRE",
  "DMARCA",
  "DVARIEDAD",
  "DOTRO1",
  "DOTRO2",
  "ATR-5",
  "ATR-6",
  "SAJU-ITEM",
  "AJU-ITEM",
  "CANT-MERC",
  "MERMAS",
  "MEDIDA",
  "PRE-UNIT",
  "ARANC-ALA",
  "NUMCOR",
  "NUMACU",
  "CODOBS1",
  "DESOBS1",
  "CODOBS2",
  "DESOBS2",
  "CODOBS3",
  "DESOBS3",
  "CODOBS4",
  "DESOBS4",
  "ARANC-NAC",
  "CIF-ITEM",
  "ADVAL-ALA",
  "ADVAL",
  "VALAD",
  "OTRO1",
  "CTA1",
  "SIGVAL1",
  "VAL1",
  "OTRO2",
  "CTA2",
  "SIGVAL2",
  "VAL2",
  "OTRO3",
  "CTA3",
  "SIGVAL3",
  "VAL3",
  "OTRO4",
  "CTA4",
  "SIGVAL4",
  "VAL4",
] as const;

export const exportFieldNames = [
  "FECHAACEPT",
  "NUMEROIDENT",
  "ADUANA",
  "TIPOOPERACION",
  "CODIGORUTEXPORTADORPPAL",
  "NRO_EXPORTADOR",
  "PORCENTAJEEXPPPAL",
  "COMUNAEXPORTADORPPAL",
  "CODIGORUTEXPSEC",
  "NRO_EXPORTADOR_SEC",
  "PORCENTAJEEXPSECUNDARIO",
  "COMUNAEXPSECUNDARIO",
  "PUERTOEMB",
  "GLOSAPUERTOEMB",
  "REGIONORIGEN",
  "TIPOCARGA",
  "VIATRANSPORTE",
  "PUERTODESEMB",
  "GLOSAPUERTODESEMB",
  "PAISDESTINO",
  "GLOSAPAISDESTINO",
  "NOMBRECIATRANSP",
  "PAISCIATRANSP",
  "RUTCIATRANSP",
  "DVRUTCIATRANSP",
  "NOMBREEMISORDOCTRANSP",
  "RUTEMISOR",
  "DVRUTEMISOR",
  "CODIGOTIPOAUTORIZA",
  "NUMEROINFORMEEXPO",
  "DVNUMEROINFORMEEXP",
  "FECHAINFORMEEXP",
  "MONEDA",
  "MODALIDADVENTA",
  "CLAUSULAVENTA",
  "FORMAPAGO",
  "VALORCLAUSULAVENTA",
  "COMISIONESEXTERIOR",
  "OTROSGASTOS",
  "VALORLIQUIDORETORNO",
  "NUMEROREGSUSP",
  "ADUANAREGSUSP",
  "PLAZOVIGENCIAREGSUSP",
  "TOTALITEM",
  "TOTALBULTOS",
  "PESOBRUTOTOTAL",
  "TOTALVALORFOB",
  "VALORFLETE",
  "CODIGOFLETE",
  "VALORSEGURO",
  "CODIGOSEG",
  "VALORCIF",
  "NUMEROPARCIALIDAD",
  "TOTALPARCIALES",
  "PARCIAL",
  "OBSERVACION",
  "NUMERODOCTOCANCELA",
  "FECHADOCTOCANCELA",
  "TIPODOCTOCANCELA",
  "PESOBRUTOCANCELA",
  "TOTALBULTOSCANCELA",
  "NUMEROITEM",
  "NOMBRE",
  "ATRIBUTO1",
  "ATRIBUTO2",
  "ATRIBUTO3",
  "ATRIBUTO4",
  "ATRIBUTO5",
  "ATRIBUTO6",
  "CODIGOARANCEL",
  "UNIDADMEDIDA",
  "CANTIDADMERCANCIA",
  "FOBUNITARIO",
  "FOBUS",
  "CODIGOOBSERVACION1",
  "VALOROBSERVACION1",
  "GLOSAOBSERVACION1",
  "CODIGOOBSERVACION2",
  "VALOROBSERVACION2",
  "GLOSAOBSERVACION2",
  "CODIGOOBSERVACION3",
  "VALOROBSERVACION3",
  "GLOSAOBSERVACION3",
  "PESOBRUTOITEM",
] as const;

export const importCodedFields = new Set([
  "TIPO_DOCTO",
  "ADU",
  "FORM",
  "ADUCTROL",
  "ADUA_RS",
  "ADU_DI",
  "CODCOMUN",
  "CODCOMRS",
  "CODPAISCON",
  "PA_ORIG",
  "PA_ADQ",
  "CODPAISCIA",
  "VIA_TRAN",
  "TRANSB",
  "PTO_EMB",
  "PTO_DESEM",
  "TPO_CARGA",
  "ALMACEN",
  "PAGO_GRAV",
  "BCO_COM",
  "CODORDIV",
  "FORM_PAGO",
  "MONEDA",
  "CL_COMPRA",
  "COD_FLE",
  "COD_SEG",
  "TPO_BUL1",
  "TPO_BUL2",
  "TPO_BUL3",
  "TPO_BUL4",
  "TPO_BUL5",
  "TPO_BUL6",
  "TPO_BUL7",
  "TPO_BUL8",
  "MEDIDA",
  "ARANC-ALA",
  "ARANC-NAC",
  "NUMCOR",
  "NUMACU",
  "CTA_OTRO",
  "CTA_OTR1",
  "CTA_OTR2",
  "CTA_OTR3",
  "CTA_OTR4",
  "CTA_OTR5",
  "CTA_OTR6",
  "CTA_OTR7",
  "ADVAL",
  "CTA1",
  "CTA2",
  "CTA3",
  "CTA4",
  "CODOBS1",
  "CODOBS2",
  "CODOBS3",
  "CODOBS4",
]);

export const exportCodedFields = new Set([
  "ADUANA",
  "TIPOOPERACION",
  "COMUNAEXPORTADORPPAL",
  "COMUNAEXPSECUNDARIO",
  "REGIONORIGEN",
  "ADUANAREGSUSP",
  "PUERTOEMB",
  "PUERTODESEMB",
  "PAISDESTINO",
  "PAISCIATRANSP",
  "TIPOCARGA",
  "VIATRANSPORTE",
  "MONEDA",
  "MODALIDADVENTA",
  "CLAUSULAVENTA",
  "FORMAPAGO",
  "CODIGOFLETE",
  "CODIGOSEG",
  "CODIGOTIPOAUTORIZA",
  "TIPODOCTOCANCELA",
  "CODIGOARANCEL",
  "UNIDADMEDIDA",
  "CODIGOOBSERVACION1",
  "CODIGOOBSERVACION2",
  "CODIGOOBSERVACION3",
]);

const rawFieldCodeTableKeys = new Map<string, string>([
  ["ADU", "chile_aduana:aduanas"],
  ["ADU_MANIF", "chile_aduana:aduanas"],
  ["ADUA_RS", "chile_aduana:aduanas"],
  ["ADUCTROL", "chile_aduana:aduanas"],
  ["ADUCON", "chile_aduana:aduanas"],
  ["ADUANACONTROL", "chile_aduana:aduanas"],
  ["ADUANAEMISORA", "chile_aduana:aduanas"],
  ["ADUANAPRESENTACION", "chile_aduana:aduanas"],
  ["CLAUSULAVENTA", "chile_aduana:clausulas_de_compra_venta"],
  ["CL_COMPRA", "chile_aduana:clausulas_de_compra_venta"],
  ["COD_FLE", "chile_aduana:moneda"],
  ["COD_SEG", "chile_aduana:moneda"],
  ["CODIGOFLETE", "chile_aduana:moneda"],
  ["CODIGOSEG", "chile_aduana:moneda"],
  ["CODPAISCIA", "chile_aduana:paises"],
  ["CODPAISCON", "chile_aduana:paises"],
  ["MONEDA", "chile_aduana:moneda"],
  ["MODALIDADVENTA", "chile_aduana:modalidades_de_venta"],
  ["PA_ADQ", "chile_aduana:paises"],
  ["PA_ORIG", "chile_aduana:paises"],
  ["PAISCONSIGNATARIO", "chile_aduana:paises"],
  ["PAISDESTINO", "chile_aduana:paises"],
  ["PAISORIGEN", "chile_aduana:paises"],
  ["PAISPUERTOEMBARQUE", "chile_aduana:paises"],
  ["PAISCIATRANSP", "chile_aduana:paises"],
  ["PTO_DESEM", "chile_aduana:puertos"],
  ["PTO_EMB", "chile_aduana:puertos"],
  ["PUERTODESEMBARQUE", "chile_aduana:puertos"],
  ["PUERTOEMBARQUE", "chile_aduana:puertos"],
  ["REG_IMP", "chile_aduana:regimen_de_importacion"],
  ["TIPOCARGA", "chile_aduana:tipos_de_carga"],
  ["TIPOOPERACION", "chile_aduana:tipos_de_operacion"],
  ["TPO_CARGA", "chile_aduana:tipos_de_carga"],
  ["UNIDMER", "chile_aduana:unidades_de_medida"],
  ["UNIDADMEDIDA", "chile_aduana:unidades_de_medida"],
  ["VIA_TRAN", "chile_aduana:vias_de_transporte"],
  ["VIATRANSPORTE", "chile_aduana:vias_de_transporte"],
]);

export function codeTableKeyForSourceField(sourceFieldName: string): string | null {
  return rawFieldCodeTableKeys.get(sourceFieldName) ?? null;
}
